version: '2'
# after changes to the file run (will recreate and restart only the necessary things): 
#   sudo su
#   docker-compose up -d
# stop running instances: 
#   sudo su
#   docker-compose stop
services:
  jenkins:
    image: jenkinsci/jenkins:2.9
    ports:
     - "8080:8080"
    volumes:
     - /export/scratch1/jenkins/home:/var/jenkins_home
    user: "jenkins"
    restart: always
    environment:
     JAVA_OPTS: "-Xmx2G -Djava.awt.headless=true"
     HOME: "/var/jenkins_home"
    tmpfs: 
      - /tmp:size=1g

  nexus:
    image: sonatype/nexus3:3.0.0
    ports: 
      - "8081:8081"
    user: "nexus"
    volumes:
    # nexus assume the user 200 is owning this folder!
     - /export/scratch1/nexus/data:/nexus-data
    restart: always

  artifactory:
    image: jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss:latest
    ports: 
      - "8082:8081"
    volumes:
     - /export/scratch1/artifactory/data:/var/opt/jfrog/artifactory/data
     - /export/scratch1/artifactory/logs:/var/opt/jfrog/artifactory/logs
     - /export/scratch1/artifactory/backups:/var/opt/jfrog/artifactory/backups
     - /export/scratch1/artifactory/etc:/var/opt/jfrog/artifactory/etc
    restart: always
  

