version: '2'
# after changes to the file run (will recreate and restart only the necessary things): 
#   sudo su
#   docker-compose up -d
# stop running instances: 
#   sudo su
#   docker-compose stop
services:
  jenkins:
    #image: swat/jenkins:2.3-alpine
    #image: jenkins:2.3
    build: 
      context: custom-jenkins/
      args:
        # if you change this rebuild:
        #   sudo su
        #   docker-compose up -d --build
        - uid=989
        - gid=989
        - JENKINS_VERSION=2.3
        - JENKINS_SHA=d3097c9c81c7d5074d71a5059d85cf8977c1568e
    ports:
     - "8080:8080"
    volumes:
     - /export/scratch1/jenkins/home:/var/jenkins_home
    user: "989"
    restart: always
    environment:
     JAVA_OPTS: "-Duser.home=/var/jenkins_home -Djava.awt.headless=true"
     HOME: "/var/jenkins_home"
     USER: "jenkins"
    tmpfs: 
      - /tmp:size=1g

  nexus:
    image: sonatype/nexus3:3.0.0
    ports: 
      - "8081:8081"
    volumes:
    # nexus assume the user 200 is owning this folder!
     - /export/scratch1/nexus/data:/nexus-data
    restart: always

  artifactory:
    image: jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss:latest
    ports: 
      - "8082:8081"
    volumes:
     - /export/scratch1/artifactory/data:/var/opt/jfrog/artifactory/data
     - /export/scratch1/artifactory/logs:/var/opt/jfrog/artifactory/logs
     - /export/scratch1/artifactory/backups:/var/opt/jfrog/artifactory/backups
     - /export/scratch1/artifactory/etc:/var/opt/jfrog/artifactory/etc
    restart: always
  

